### ISSUE TITLE
Issue pairing

### ISSUE THREAD

**Issue by christianmagill** [edc1591/alfred-itunes-dj#4]
**Got this issue resolved.. see comment below**
Hi I'm having an issue pairing. I have tried several times...

I am running RVM

Here is my debug output

```
Starting debug for 'iTunes DJ'

[2016-12-13 19:36:49][ERROR: action.script] /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/gserver.rb:249:in `initialize': Address already in use - bind(2) (Errno::EADDRINUSE)
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/gserver.rb:249:in `new'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/gserver.rb:249:in `block in start'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/gserver.rb:245:in `synchronize'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/gserver.rb:245:in `start'
	from /Users/christianmagill/Library/Application Support/Alfred 3/Alfred.alfredpreferences/workflows/user.workflow.A7F7F476-CE30-4D25-BD8E-328614AFAEEA/vendor/ruby/2.0.0/gems/dacpclient-0.3.4/lib/dacpclient/pairingserver.rb:32:in `start'
	from /Users/christianmagill/Library/Application Support/Alfred 3/Alfred.alfredpreferences/workflows/user.workflow.A7F7F476-CE30-4D25-BD8E-328614AFAEEA/itunesdj.rb:28:in `pair'
	from /Users/christianmagill/Library/Caches/com.runningwithcrayons.Alfred-3/Workflow Scripts/C9F0851E-6F11-4B6E-9274-9F498D8E4744:12:in `<main>'
[2016-12-13 19:37:03][ERROR: action.script] /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/gserver.rb:249:in `initialize': Address already in use - bind(2) (Errno::EADDRINUSE)
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/gserver.rb:249:in `new'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/gserver.rb:249:in `block in start'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/gserver.rb:245:in `synchronize'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/gserver.rb:245:in `start'
	from /Users/christianmagill/Library/Application Support/Alfred 3/Alfred.alfredpreferences/workflows/user.workflow.A7F7F476-CE30-4D25-BD8E-328614AFAEEA/vendor/ruby/2.0.0/gems/dacpclient-0.3.4/lib/dacpclient/pairingserver.rb:32:in `start'
	from /Users/christianmagill/Library/Application Support/Alfred 3/Alfred.alfredpreferences/workflows/user.workflow.A7F7F476-CE30-4D25-BD8E-328614AFAEEA/itunesdj.rb:28:in `pair'
	from /Users/christianmagill/Library/Caches/com.runningwithcrayons.Alfred-3/Workflow Scripts/C9F0851E-6F11-4B6E-9274-9F498D8E4744:12:in `<main>'
```

I am able to install dapcclient using `rvm system && sudo gem install dapcclient`, however when I run the login commmand I get

```
dacpclient login                                                   [19:39:42]
/usr/local/bin/dacpclient:23:in `load': cannot load such file -- /Library/Ruby/Gems/2.0.0/gems/dacpclient-0.3.4/bin/dacpclient (LoadError)
	from /usr/local/bin/dacpclient:23:in `<main>'
```

Thanks for any help!

**Comment by christianmagill** [comment]
Got things working after updating Ruby and restarting a couple times.
